import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Frontend Masters Next 13 Intro',
  description: 'Generated by create next app',
}

const links = [
  {
    href: '/', label: "Home",
  },
  {
    href: '/docs', label: "Docs",
  },
  {
    href: '/todos', label: "To Dos",
  },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark:text-white dark:bg-teal-700 bg-teal-200 text-teal-800`}>
        <header>
          <nav className='flex items-center justify-between flex-wrap bg-teal-500 dark:bg-teal-900 p-6 text-white'>
            <div className='container mx-auto'>
              <ul className='flex items-center'>
                {links.map(({ href, label }, i) => (
                  <li key={`${i}`} className='mx-6'>
                    <Link href={href}>
                      {label}
                    </Link>
                  </li>
                ))}
              </ul>
            </div>
          </nav>
       
        </header>
        <main className='container mx-auto'>
          <div className=''>
            <p className='py-3 mb-3 border-b border-white'>Root Layout</p>
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
